import React from 'react';
import { View, Text, ScrollView, StyleSheet, TouchableOpacity } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { useThemeColors } from '../../context/ThemeContext';
import { fontSizes, spacing, radii } from '../../theme';

const SECTIONS = [
  {
    title: '1. Information We Collect',
    body: `We collect information you provide directly (name, email, phone number, username, bio) and information generated by your use of the App (posts, XP, wallet activity, login timestamps). We may also collect device information such as OS version and device model for crash diagnostics.`,
  },
  {
    title: '2. How We Use Your Information',
    body: `Your information is used to:\n• Operate and improve the App\n• Process XP rewards and wallet transactions\n• Send notifications relevant to your activity\n• Detect and prevent fraud or abuse\n• Comply with legal obligations`,
  },
  {
    title: '3. Data Sharing',
    body: `We do not sell your personal data. We may share data with:\n• Service providers necessary to operate the App (e.g., payment processors, cloud hosting)\n• Law enforcement when required by law\n• Other users — only profile info you've made public`,
  },
  {
    title: '4. Wallet & Financial Data',
    body: `Wallet and transaction data are stored securely. UPI IDs are stored encrypted. We do not store full payment credentials. All financial transactions are processed via RBI-compliant payment infrastructure.`,
  },
  {
    title: '5. Data Security',
    body: `We implement industry-standard security measures including bcrypt password hashing, encrypted token storage, and TLS in transit. App Lock (PIN + Biometric) is available for additional local device security.`,
  },
  {
    title: '6. Data Retention',
    body: `We retain your data for as long as your account is active or as needed to provide services. You may request account deletion via Settings → Account Actions → Delete Account. Deleted accounts are permanently removed within 30 days.`,
  },
  {
    title: '7. Your Rights',
    body: `You have the right to:\n• Access your personal data\n• Correct inaccurate data\n• Request deletion of your account\n• Withdraw consent for optional data processing\n\nTo exercise these rights, contact us at privacy@taddle.app`,
  },
  {
    title: '8. Cookies & Local Storage',
    body: `The App uses local device storage (SecureStore) to persist authentication tokens and user preferences such as theme mode. No third-party tracking cookies are used.`,
  },
  {
    title: '9. Changes to this Policy',
    body: `We may update this Privacy Policy periodically. You will be notified of material changes via the App. Continued use after changes constitutes acceptance.`,
  },
  {
    title: '10. Contact Us',
    body: `For privacy-related questions or data requests, contact us at:\nprivacy@taddle.app`,
  },
];

export default function PrivacyScreen() {
  const navigation = useNavigation<any>();
  const colors     = useThemeColors();

  return (
    <SafeAreaView style={[styles.root, { backgroundColor: colors.bg.base }]}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={[styles.iconBtn, { borderColor: colors.border }]}>
          <Ionicons name="arrow-back" size={20} color={colors.text.primary} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.text.primary }]}>Privacy Policy</Text>
        <View style={{ width: 38 }} />
      </View>

      <ScrollView contentContainerStyle={styles.body} showsVerticalScrollIndicator={false}>
        <Text style={[styles.updated, { color: colors.text.muted }]}>Last updated: July 2026</Text>
        <Text style={[styles.intro, { color: colors.text.secondary }]}>
          Your privacy matters. This policy explains what data Taddle collects, how we use it, and your rights.
        </Text>

        {SECTIONS.map((s, i) => (
          <View key={i} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: colors.text.primary }]}>{s.title}</Text>
            <Text style={[styles.sectionBody, { color: colors.text.secondary }]}>{s.body}</Text>
          </View>
        ))}
        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root:         { flex: 1 },
  header:       { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, paddingVertical: 12, borderBottomWidth: 1, gap: 12 },
  iconBtn:      { width: 38, height: 38, borderRadius: radii.md, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  headerTitle:  { flex: 1, fontSize: fontSizes.xl, fontWeight: '800' },
  body:         { padding: spacing.xl },
  updated:      { fontSize: fontSizes.xs, marginBottom: spacing.sm },
  intro:        { fontSize: fontSizes.md, lineHeight: 22, marginBottom: spacing.xl },
  section:      { marginBottom: spacing.xl },
  sectionTitle: { fontSize: fontSizes.md, fontWeight: '800', marginBottom: spacing.sm },
  sectionBody:  { fontSize: fontSizes.sm, lineHeight: 22 },
});
