import { StyleSheet } from "react-native";
import { fontSizes, spacing, radii, type ColorPalette } from "../../theme";

// ── Search screen + row styles ────────────────────────────────────────────────
// Shared by SearchScreen (its own chrome) and the SearchRows components (via
// ctx.styles). Keeping the factory here means SearchRows can type its ctx with
// SearchStyles directly — no type-only import back into the screen module.
export function makeStyles(c: ColorPalette) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.bg.base,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: spacing.sm,
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
      backgroundColor: c.bg.surface,
    },
    backBtn: {
      padding: spacing.sm,
    },
    searchBar: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.bg.elevated,
      borderRadius: radii.full,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginRight: spacing.sm,
      borderWidth: 1,
      borderColor: c.border,
    },
    // Suggestion dropdown — @user / c/community autocomplete while typing.
    suggestionBox: {
      marginHorizontal: spacing.sm,
      marginTop: 4,
      backgroundColor: c.bg.surface,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: c.border,
      overflow: "hidden",
    },
    suggestionLabel: {
      fontSize: fontSizes.xs,
      fontWeight: "700",
      color: c.text.muted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 4,
    },
    suggestionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: c.border,
    },
    suggestionAvatar: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.bg.elevated,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    suggestionAvatarImg: { width: "100%", height: "100%" },
    suggestionName: {
      fontSize: fontSizes.sm,
      fontWeight: "700",
      color: c.text.primary,
    },
    suggestionHandle: {
      fontSize: fontSizes.xs,
      color: c.text.muted,
      marginTop: 1,
    },
    // Chip inside the search bar — @user / c/community filter chips.
    filterChip: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      borderRadius: radii.full,
      paddingHorizontal: 8,
      paddingVertical: 4,
      marginLeft: 8,
      maxWidth: 130,
    },
    filterChipText: {
      fontSize: fontSizes.xs,
      fontWeight: "700",
      flexShrink: 1,
    },
    searchInput: {
      flex: 1,
      marginLeft: 8,
      marginRight: 8,
      fontSize: fontSizes.md,
      color: c.text.primary,
    },
    tabsContainer: {
      paddingHorizontal: spacing.md,
      paddingVertical: 12,
      gap: 12,
      borderBottomWidth: 1,
      borderBottomColor: c.border,
    },
    tabBtn: {
      paddingVertical: 6,
      paddingHorizontal: 14,
      borderRadius: radii.full,
      backgroundColor: c.bg.elevated,
      borderWidth: 1,
      borderColor: c.border,
    },
    tabBtnActive: {
      backgroundColor: c.primaryLight,
      borderColor: c.primaryLight,
    },
    tabText: {
      fontSize: fontSizes.sm,
      fontWeight: "600",
      color: c.text.secondary,
    },
    tabTextActive: {
      color: "#fff",
    },
    listContent: {
      paddingVertical: spacing.md,
      gap: 4,
    },
    discoverBanner: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      marginHorizontal: spacing.md,
      marginTop: 2,
      marginBottom: 8,
    },
    discoverText: {
      fontSize: fontSizes.md,
      fontWeight: "700",
      color: c.text.primary,
    },
    centerBox: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      paddingTop: 60,
      paddingHorizontal: spacing.xl,
    },
    emptyText: {
      marginTop: 16,
      fontSize: fontSizes.md,
      color: c.text.muted,
      textAlign: "center",
    },
    peopleRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.bg.card,
      padding: spacing.md,
      marginHorizontal: spacing.md,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: c.border,
    },
    avatarBubble: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.bg.elevated,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      overflow: "hidden",
    },
    avatarImg: {
      width: "100%",
      height: "100%",
    },
    peopleInfo: {
      flex: 1,
    },
    peopleName: {
      fontSize: fontSizes.md,
      fontWeight: "700",
      color: c.text.primary,
    },
    peopleHandle: {
      fontSize: fontSizes.sm,
      color: c.text.muted,
      marginTop: 2,
    },
    peopleMeta: {
      fontSize: fontSizes.xs,
      color: c.text.muted,
      marginTop: 2,
      opacity: 0.8,
    },
    // Comment result row — quote the comment text below the author line.
    commentContent: {
      fontSize: fontSizes.sm,
      color: c.text.primary,
      marginTop: 4,
      lineHeight: 20,
    },
    mediaThumbWrap: {
      width: 44,
      height: 44,
      borderRadius: 10,
      backgroundColor: c.bg.elevated,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
      overflow: "hidden",
    },
    mediaThumb: {
      width: "100%",
      height: "100%",
    },
    // Fallback card for backend result kinds without a dedicated renderer —
    // icon bubble + type name + title, matching the people row layout.
    genericRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.bg.card,
      padding: spacing.md,
      marginHorizontal: spacing.md,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: c.border,
    },
    genericIconBubble: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.bg.elevated,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    genericTypeLabel: {
      fontSize: fontSizes.xs,
      fontWeight: "700",
      color: c.text.muted,
      textTransform: "capitalize",
      letterSpacing: 0.4,
      marginBottom: 2,
    },
    hashtagRow: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: c.bg.card,
      padding: spacing.md,
      marginHorizontal: spacing.md,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: c.border,
    },
    // Poll result card — author line, question, options with vote bars.
    pollCard: {
      backgroundColor: c.bg.card,
      padding: spacing.md,
      marginHorizontal: spacing.md,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: c.border,
    },
    pollHeader: {
      flexDirection: "row",
      alignItems: "center",
    },
    pollQuestion: {
      fontSize: fontSizes.md,
      fontWeight: "700",
      color: c.text.primary,
      marginTop: 10,
      lineHeight: 22,
    },
    pollOption: {
      marginTop: 8,
    },
    pollOptionTextRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    pollOptionText: {
      flex: 1,
      fontSize: fontSizes.sm,
      color: c.text.primary,
      marginRight: 8,
      lineHeight: 18,
    },
    pollOptionPct: {
      fontSize: fontSizes.sm,
      fontWeight: "700",
      color: c.text.muted,
    },
    pollBarTrack: {
      height: 6,
      borderRadius: 3,
      backgroundColor: c.bg.elevated,
      marginTop: 4,
      overflow: "hidden",
    },
    pollBarFill: {
      height: "100%",
      borderRadius: 3,
      backgroundColor: c.primaryLight,
    },
    hashIconBubble: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.bg.surface,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    hashIcon: {
      color: c.text.secondary,
      fontWeight: "bold",
    },
    hashtagText: {
      fontSize: fontSizes.md,
      fontWeight: "600",
      color: c.text.primary,
    },
    filterIconButton: {
      padding: spacing.md,
      justifyContent: "center",
      alignItems: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: c.bg.base,
      borderTopLeftRadius: radii.xl,
      borderTopRightRadius: radii.xl,
      padding: spacing.lg,
      paddingBottom: 40,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: spacing.lg,
    },
    modalTitle: {
      fontSize: fontSizes.lg,
      fontWeight: "800",
      color: c.text.primary,
    },
    modalCloseBtn: {
      padding: 4,
      backgroundColor: c.bg.surface,
      borderRadius: radii.full,
    },
    filterGroup: {
      marginBottom: spacing.lg,
    },
    filterGroupTitle: {
      fontSize: fontSizes.xs,
      fontWeight: "700",
      color: c.text.muted,
      marginBottom: spacing.sm,
      letterSpacing: 0.5,
    },
    filterRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    sheetFilterChip: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: radii.full,
      backgroundColor: c.bg.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    sheetFilterChipActive: {
      backgroundColor: c.primaryLight,
      borderColor: c.primaryLight,
    },
    sheetFilterChipText: {
      fontSize: fontSizes.sm,
      fontWeight: "600",
      color: c.text.secondary,
    },
    sheetFilterChipTextActive: {
      color: "#fff",
    },
    applyFilterBtn: {
      backgroundColor: c.primaryLight,
      borderRadius: radii.lg,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: spacing.md,
    },
    applyFilterText: {
      color: "#fff",
      fontSize: fontSizes.md,
      fontWeight: "700",
    },
    recentSearchesContainer: {
      paddingTop: spacing.lg,
      paddingHorizontal: spacing.md,
    },
    recentHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
    },
    recentTitle: {
      fontSize: fontSizes.sm,
      fontWeight: "700",
      color: c.text.muted,
      textTransform: "uppercase",
      letterSpacing: 0.5,
    },
    recentClear: {
      fontSize: fontSizes.sm,
      fontWeight: "600",
      color: c.primaryLight,
    },
    recentRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    recentText: {
      flex: 1,
      fontSize: fontSizes.md,
      color: c.text.primary,
      marginLeft: 12,
    },
  });
}

export type SearchStyles = ReturnType<typeof makeStyles>;
