import { StyleSheet } from "react-native";
import { CHAT_MAX_H } from "./shared";

export const styles = StyleSheet.create({
  gameFill: { flex: 1, alignItems: "center", paddingTop: 6, paddingBottom: 6 },
  fullCenter: { flex: 1, justifyContent: "center", alignItems: "center" },
  splashEmoji: { fontSize: 64, marginBottom: 10 },
  splashTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: "#F1F5F9",
    marginBottom: 5,
  },
  splashSub: { fontSize: 14, color: "#64748B" },

  dieGlowWrapCountdown: { borderColor: "#0F172A", shadowColor: "#FFFFFF" },

  boardWrap: {
    flex: 1,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 14,
    padding: 3,
  },
  board: {
    borderRadius: 10,
    overflow: "hidden",
    borderWidth: 1.5,
    borderColor: "rgba(124,58,237,0.4)",
    elevation: 20,
    shadowColor: "#7C3AED",
    shadowOpacity: 0.45,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 4 },
  },

  tokenOuter: {
    position: "absolute",
    inset: 0,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  tokenShine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "50%",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  tokenInner: { justifyContent: "center", alignItems: "center" },
  tokenLabel: { fontWeight: "900", color: "#FFF" },

  cornerCard: {
    position: "relative",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 16,
    borderWidth: 1.5,
    shadowColor: "#6FA0FF",
    shadowOpacity: 0.45,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    width: 92,
  },
  cornerCardCompact: { paddingVertical: 3, paddingHorizontal: 5, width: 72 },
  cornerAvatarFrame: {
    width: 42,
    height: 42,
    borderRadius: 12,
    borderWidth: 2,
    padding: 2,
    position: "relative",
    backgroundColor: "rgba(8,26,100,0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  cornerAvatarFrameCompact: { width: 30, height: 30, borderRadius: 9 },
  cornerAvatar: { width: 34, height: 34, borderRadius: 9 },
  cornerAvatarCompact: { width: 22, height: 22, borderRadius: 6 },
  cornerAvatarPh: {
    width: 34,
    height: 34,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },
  cornerAvatarPhCompact: { width: 22, height: 22, borderRadius: 6 },
  cornerAvatarInitial: { color: "#FFF", fontWeight: "900", fontSize: 15 },
  cornerAvatarInitialCompact: { fontSize: 11 },
  cornerLevelBadge: {
    position: "absolute",
    bottom: -3,
    right: -3,
    minWidth: 15,
    height: 15,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    borderWidth: 1.5,
    borderColor: "#0A1B4D",
  },
  cornerLevelBadgeCompact: {
    minWidth: 12,
    height: 12,
    borderRadius: 6,
    paddingHorizontal: 2,
    borderWidth: 1.2,
  },
  cornerLevelText: {
    fontSize: 8,
    fontWeight: "900",
    color: "#1A0A00",
    lineHeight: 9,
  },
  cornerLevelTextCompact: { fontSize: 7, lineHeight: 8 },
  cornerName: {
    fontSize: 10,
    fontWeight: "800",
    marginTop: 4,
    maxWidth: 74,
    textAlign: "center",
    lineHeight: 13,
  },
  cornerNameCompact: {
    fontSize: 8,
    marginTop: 2,
    lineHeight: 10,
    maxWidth: 60,
  },
  cornerPct: { fontSize: 11, fontWeight: "900", marginTop: 1 },

  dieArea: { position: "absolute", alignItems: "center", zIndex: 40 },
  dieGlowWrap: {
    width: 56,
    height: 56,
    borderRadius: 15,
    borderWidth: 2.5,
    borderColor: "#CBD5E1",
    backgroundColor: "#FFFFFF",
    elevation: 14,
    shadowColor: "#64748B",
    shadowOpacity: 0.8,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 0 },
  },
  dieGlowWrapRolled: { borderColor: "#0F172A", shadowColor: "#FFFFFF" },
  dieMoveChip: {
    position: "absolute",
    bottom: -18,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  dieMoveChipPill: {
    minWidth: 34,
    height: 21,
    borderRadius: 11,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingHorizontal: 8,
    backgroundColor: "#0F172A",
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 1 },
  },
  dieMoveChipText: { fontSize: 10, fontWeight: "900", color: "#FFFFFF" },
  dieBody: {
    width: 56,
    height: 56,
    borderRadius: 13,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  dot: {
    position: "absolute",
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#F8FAFC",
    transform: [{ translateX: -5 }, { translateY: -5 }],
  },
  dotDark: { backgroundColor: "#0F172A" },
  diceIdle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(15,23,42,0.06)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "rgba(15,23,42,0.2)",
  },
  diceIdlePip: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    backgroundColor: "rgba(15,23,42,0.4)",
  },


  bubble: {
    backgroundColor: "rgba(8,16,64,0.95)",
    borderRadius: 12,
    borderWidth: 1,
    borderLeftWidth: 3,
    borderColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    elevation: 8,
  },
  bubbleText: { color: "#E2E8F0", fontSize: 12, fontWeight: "600" },


  toast: {
    position: "absolute",
    bottom: 96,
    alignSelf: "center",
    borderRadius: 24,
    overflow: "hidden",
    elevation: 18,
  },
  toastInner: {
    paddingHorizontal: 22,
    paddingVertical: 11,
    borderRadius: 24,
    borderWidth: 1.5,
    borderColor: "rgba(124,58,237,0.45)",
  },
  toastText: { color: "#F1F5F9", fontSize: 15, fontWeight: "900" },
});
